/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 15/07/2012, 06:21:34 PM
 */
package frames;

import clases.DBConnect;
import clases.Usuario;
import com.mysql.jdbc.Blob;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileView;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Edgar
 */
public class FramePrincipal extends javax.swing.JFrame {
    private Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    private int i=0;
    private DBConnect db;
    private double zoom=1.0;
    private String ruta="";
    private Usuario user;
    private jDProductos a;
    private jDClientes b;
    private jDPersonal c;
    /** Creates new form FramePrincipal */
    public FramePrincipal(DBConnect con) {
        initComponents();
        
        this.setIconImage(imagen); 
        setLocationRelativeTo(null);
        Usuario.setText(con.getUser());
        db = con;
        this.user = new Usuario();
        a = new jDProductos(this, true,db,user.getNivelUsuario());
        this.user.setAliasUsuario(con.getUser());
        
        jMIniSesion.setEnabled(false);
        ResultSet nrovendr = db.Listar("*", "usuario", "where Alias_usu='"+Usuario.getText()+"'");
        try {
            if(nrovendr.next()){
                this.user.setNomUsuario(nrovendr.getString(2)+" "+nrovendr.getString(3));
                this.user.setNivelUsuario(nrovendr.getString("Nivel_usu"));
                Usuario.setText("Bienvenid@ "+nrovendr.getString(2)+" "+nrovendr.getString(3));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(jDnventa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setTitle("Easy Soft - Farepar Importaciones S.R.L. - "+user.getNivelUsuario());
        this.mostrarImagen();
        this.autorizar();
 }
 
    private void mostrarImagen(){ 
        String codigo;
        
        ResultSet rs = db.Listar("*", "usuario", "where Alias_usu='"+db.getUser()+"'");
        
        try{
            rs.next();
            Blob blob = (Blob) rs.getBlob("Imagen_usu");
            jTextArea1.setText(rs.getString("Notas_usu"));
            byte [] data = blob.getBytes(1,(int) blob.length());
            BufferedImage img = null;
            img = ImageIO.read(new ByteArrayInputStream(data));
            jXImageView1.setImage(img);
            jXImageView1.setScale(rs.getDouble("zoom_image"));
            zoom = rs.getDouble("zoom_image");
        } catch ( Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPImagen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        Usuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jBModif = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jPBotones = new javax.swing.JPanel();
        jBProductos = new javax.swing.JButton();
        jBPacientes = new javax.swing.JButton();
        jBVendedor = new javax.swing.JButton();
        jBVentas = new javax.swing.JButton();
        jBPresup = new javax.swing.JButton();
        jBCompra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSesion = new javax.swing.JMenu();
        jMIniSesion = new javax.swing.JMenuItem();
        jMCambUsu = new javax.swing.JMenuItem();
        jMAgrUsu = new javax.swing.JMenuItem();
        jMCerrarSesion = new javax.swing.JMenuItem();
        jMproveedor = new javax.swing.JMenu();
        jmVerProveedores = new javax.swing.JMenuItem();
        jmAgregarProveedor = new javax.swing.JMenuItem();
        JMReports = new javax.swing.JMenu();
        jMVentas = new javax.swing.JMenu();
        jMVentsDias = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMCaja = new javax.swing.JMenu();
        jMCajaDiaria = new javax.swing.JMenuItem();
        jMCajaPeridic = new javax.swing.JMenuItem();
        jMClientes = new javax.swing.JMenu();
        jMOrd_p_Cod = new javax.swing.JMenuItem();
        jMOrd_p_Nomb = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMP_Ord_p_Cod = new javax.swing.JMenuItem();
        jMP_Ord_p_Nomb = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMOrd_p_Gastado = new javax.swing.JMenuItem();
        jMayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shutdown.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jXImageView1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jXImageView1MouseWheelMoved(evt);
            }
        });
        jXImageView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXImageView1MouseClicked(evt);
            }
        });
        jXImageView1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXImageView1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        Usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Usuario.setText("Bienvenido, Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario)
                    .addComponent(jXImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTextArea1MouseWheelMoved(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Para modificar las notas, presionar Modificar");

        jBModif.setText("Modificar");
        jBModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.setToolTipText("Guarda las Modificaciones de la pantalla principal");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPImagenLayout = new javax.swing.GroupLayout(jPImagen);
        jPImagen.setLayout(jPImagenLayout);
        jPImagenLayout.setHorizontalGroup(
            jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPImagenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPImagenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPImagenLayout.createSequentialGroup()
                        .addGroup(jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPImagenLayout.createSequentialGroup()
                                .addGroup(jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPImagenLayout.createSequentialGroup()
                                        .addComponent(jBModif)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBGuardar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPImagenLayout.setVerticalGroup(
            jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModif)
                    .addComponent(jBGuardar))
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPImagenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jBProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Products_32x32.png"))); // NOI18N
        jBProductos.setText("Productos");
        jBProductos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProductosActionPerformed(evt);
            }
        });
        jBProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBProductosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBProductosKeyReleased(evt);
            }
        });

        jBPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes_32x32.png"))); // NOI18N
        jBPacientes.setText("Clientes");
        jBPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPacientesActionPerformed(evt);
            }
        });
        jBPacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPacientesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBPacientesKeyReleased(evt);
            }
        });

        jBVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vendedor_32x32.png"))); // NOI18N
        jBVendedor.setText("Personal");
        jBVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVendedorActionPerformed(evt);
            }
        });
        jBVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBVendedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBVendedorKeyReleased(evt);
            }
        });

        jBVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ventas_32x32.png"))); // NOI18N
        jBVentas.setText("Ventas");
        jBVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVentasActionPerformed(evt);
            }
        });
        jBVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBVentasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBVentasKeyReleased(evt);
            }
        });

        jBPresup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_presupuesto.png"))); // NOI18N
        jBPresup.setText("Presupuesto");
        jBPresup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPresup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPresup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPresupActionPerformed(evt);
            }
        });
        jBPresup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPresupKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBPresupKeyReleased(evt);
            }
        });

        jBCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clipboard.png"))); // NOI18N
        jBCompra.setText("Compra");
        jBCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompraActionPerformed(evt);
            }
        });
        jBCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCompraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBCompraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotonesLayout.createSequentialGroup()
                .addComponent(jBProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jBVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jBVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jBPresup, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jBCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBPresup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBar1.setAlignmentX(240.0F);

        jmSesion.setMnemonic('s');
        jmSesion.setText("Sesion");

        jMIniSesion.setMnemonic('I');
        jMIniSesion.setText("Iniciar Sesion");
        jMIniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIniSesionActionPerformed(evt);
            }
        });
        jmSesion.add(jMIniSesion);

        jMCambUsu.setMnemonic('C');
        jMCambUsu.setText("Cambiar  de Usuario");
        jMCambUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCambUsuActionPerformed(evt);
            }
        });
        jmSesion.add(jMCambUsu);

        jMAgrUsu.setMnemonic('U');
        jMAgrUsu.setText("Agregar Usuario");
        jMAgrUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAgrUsuActionPerformed(evt);
            }
        });
        jmSesion.add(jMAgrUsu);

        jMCerrarSesion.setMnemonic('T');
        jMCerrarSesion.setText("Terminar Sesion");
        jMCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCerrarSesionActionPerformed(evt);
            }
        });
        jmSesion.add(jMCerrarSesion);

        jMenuBar1.add(jmSesion);

        jMproveedor.setMnemonic('p');
        jMproveedor.setText("Proveedores");

        jmVerProveedores.setMnemonic('V');
        jmVerProveedores.setText("Ver Proveedores");
        jmVerProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerProveedoresActionPerformed(evt);
            }
        });
        jMproveedor.add(jmVerProveedores);

        jmAgregarProveedor.setMnemonic('A');
        jmAgregarProveedor.setText("Agregar Proveedor");
        jmAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarProveedorActionPerformed(evt);
            }
        });
        jMproveedor.add(jmAgregarProveedor);

        jMenuBar1.add(jMproveedor);

        JMReports.setText("Reportes");

        jMVentas.setText("Ventas");

        jMVentsDias.setText("Ventas Diarias");
        jMVentsDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVentsDiasActionPerformed(evt);
            }
        });
        jMVentas.add(jMVentsDias);

        jMenuItem1.setText("Producto Más Vendido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMVentas.add(jMenuItem1);

        JMReports.add(jMVentas);

        jMCaja.setText("Caja");

        jMCajaDiaria.setText("Reporte De Caja Diaria");
        jMCaja.add(jMCajaDiaria);

        jMCajaPeridic.setText("Reporte De Caja Periodica");
        jMCaja.add(jMCajaPeridic);

        JMReports.add(jMCaja);

        jMClientes.setText("Clientes");

        jMOrd_p_Cod.setText("Reporte Ordenados Por Código");
        jMClientes.add(jMOrd_p_Cod);

        jMOrd_p_Nomb.setText("Reporte Ordenados Por Nombre");
        jMClientes.add(jMOrd_p_Nomb);
        jMClientes.add(jSeparator1);

        jMP_Ord_p_Cod.setText("Reporte Parcial Ordenado Por Código");
        jMClientes.add(jMP_Ord_p_Cod);

        jMP_Ord_p_Nomb.setText("Reporte Parcial Ordenado Por Nombre");
        jMClientes.add(jMP_Ord_p_Nomb);
        jMClientes.add(jSeparator2);

        jMOrd_p_Gastado.setText("Reporte Ordenado Por Dinero Gastado Por Cliente");
        jMClientes.add(jMOrd_p_Gastado);

        JMReports.add(jMClientes);

        jMenuBar1.add(JMReports);

        jMayuda.setMnemonic('A');
        jMayuda.setText("Ayuda");
        jMayuda.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMayudaMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuBar1.add(jMayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        // TODO add your handling code here:
        int w=jPImagen.getWidth();
        int h=jPImagen.getHeight();
        mipanel pp = new mipanel(w,h);
        jPImagen.add(pp);
        jPImagen.repaint();
    }                                    

     */
    private void jBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProductosActionPerformed
            
            a.setVisible(true);
    }//GEN-LAST:event_jBProductosActionPerformed

    private void jBPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPacientesActionPerformed
            b = new jDClientes(this, true,db,user);
            b.setVisible(true);
    }//GEN-LAST:event_jBPacientesActionPerformed

    private void jBVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVendedorActionPerformed
        c = new jDPersonal(this, true,db);
        c.setVisible(true);
    }//GEN-LAST:event_jBVendedorActionPerformed

    private void jBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVentasActionPerformed
      new jDVentas(this, true, db,user.getNivelUsuario()).setVisible(true);
    }//GEN-LAST:event_jBVentasActionPerformed

    private void jBCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompraActionPerformed

        jDCompras a = new jDCompras(this, true,db,user.getNivelUsuario());
        a.setVisible(true);
    }//GEN-LAST:event_jBCompraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        db.desconectar();
        
    }//GEN-LAST:event_formWindowClosed

    private void jMCambUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCambUsuActionPerformed
        // TODO add your handling code here:
        new FrmLogon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMCambUsuActionPerformed

    private void jMIniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIniSesionActionPerformed
        // TODO add your handling code here:
        db.desconectar();
        new FrmLogon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIniSesionActionPerformed

    private void jMCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCerrarSesionActionPerformed
        // TODO add your handling code here:
       int resultado = JOptionPane.showConfirmDialog(null, "¿En realidad desea cerrar sesión?");
       if(resultado == JOptionPane.YES_OPTION){
           Usuario.setText("Desconectado");
           jMIniSesion.setEnabled(true);
           jMAgrUsu.setEnabled(false);
           jMCerrarSesion.setEnabled(false);
           jMCambUsu.setEnabled(false);
           jMproveedor.setEnabled(false);
           habilitador(false);
           db.desconectar();
       }
    }//GEN-LAST:event_jMCerrarSesionActionPerformed

    private void jMAgrUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAgrUsuActionPerformed
        // TODO add your handling code here:
        new JDNuevoUsu(this, true, db, "Usuario").setVisible(true);
    }//GEN-LAST:event_jMAgrUsuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarProveedorActionPerformed
            new jDnProveedor(this, true, db, 0).setVisible(true);
    }//GEN-LAST:event_jmAgregarProveedorActionPerformed

    private void jmVerProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerProveedoresActionPerformed
        
            new JDProveedor(this, true, db,0).setVisible(true);
    }//GEN-LAST:event_jmVerProveedoresActionPerformed

    private void jMayudaMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMayudaMenuKeyPressed
        
    }//GEN-LAST:event_jMayudaMenuKeyPressed

    private void jBProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBProductosKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBPacientes.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBCompra.requestFocus();
        }
    }//GEN-LAST:event_jBProductosKeyPressed

    private void jBPacientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPacientesKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBVendedor.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBProductos.requestFocus();
        }
    }//GEN-LAST:event_jBPacientesKeyPressed

    private void jBVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVendedorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBVentas.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBPacientes.requestFocus();
        }
    }//GEN-LAST:event_jBVendedorKeyPressed

    private void jBVentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVentasKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBPresup.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBVendedor.requestFocus();
        }
    }//GEN-LAST:event_jBVentasKeyPressed

    private void jBCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCompraKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBProductos.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBPresup.requestFocus();
        }
    }//GEN-LAST:event_jBCompraKeyPressed

    private void jMVentsDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVentsDiasActionPerformed
        jDViewDate a = new jDViewDate(this, true,"Seleccione una Fecha:");
        a.setVisible(true);
        ResultSet r=null;
        if(a.fecha!=null){
            
         try{
           r=db.Listar("*", "vistaventa", "where `Fecha_venta` >= '"+(a.fecha.getYear()+1900)+"-"
                   +(a.fecha.getMonth()+1)+"-"+(a.fecha.getDate())+"' order by Id_venta ASC");
          

           
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        
        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/Ventas.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
            
            
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                        

     
        
    }//GEN-LAST:event_jMVentsDiasActionPerformed

    private void jBProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBProductosKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBVendedor.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBPacientes.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBProductosKeyReleased

    private void jBPacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPacientesKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBVendedor.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPacientesKeyReleased

    private void jBVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVendedorKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBPresup.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBVendedorKeyReleased

    private void jBVentasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVentasKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBPresup.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
       
    }//GEN-LAST:event_jBVentasKeyReleased

    private void jBCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCompraKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBProductos.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBPacientes.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBCompraKeyReleased

    private void jXImageView1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXImageView1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_PLUS){
            zoom+=0.1;
            jXImageView1.setScale(zoom);
        }
        if(evt.getKeyCode()==KeyEvent.VK_MINUS){
            zoom-=0.1;
            jXImageView1.setScale(zoom);
        }
    }//GEN-LAST:event_jXImageView1KeyReleased

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTextArea1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTextArea1MouseWheelMoved
       
    }//GEN-LAST:event_jTextArea1MouseWheelMoved

    private void jXImageView1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jXImageView1MouseWheelMoved
         if(evt.getPreciseWheelRotation()>0){
            zoom-=0.1;
            jXImageView1.setScale(zoom);
        }else{
            zoom+=0.1;
            jXImageView1.setScale(zoom);
        }
    }//GEN-LAST:event_jXImageView1MouseWheelMoved

    private void jBModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifActionPerformed
        jTextArea1.setEditable(true);
        jTextArea1.requestFocus();
    }//GEN-LAST:event_jBModifActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
            int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente guardar las Modificaciones realizadas?", "Atención", JOptionPane.YES_NO_OPTION);
            if(opcion==JOptionPane.YES_OPTION){
                
                if(ruta==""){
                    db.actualizarRegistro("usuario", " Notas_usu= '"+jTextArea1.getText()+"' , zoom_image="+zoom, "where Alias_usu= '"+db.getUser()+"'");
                }else{
                    String mods[] = new String[2];
                    db.actualizarRegistro("usu", " zoom_image="+zoom, "where Alias_usu= '"+db.getUser()+"'");
                    mods[0] = jTextArea1.getText();
                    mods[1] = db.getUser();
                    
                    FileInputStream foto = null,foto1 = null;
                    try {
                        foto = new FileInputStream(ruta);
                        foto1 = new FileInputStream(ruta);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    if(db.actualizarRegistro(mods,foto1,"usuario")){
                        JOptionPane.showMessageDialog(rootPane, "Los Cambios han sido guardados correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                        
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un Error al momento de guardar los Cambios", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                   
                    
                }
                
                
            }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jXImageView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXImageView1MouseClicked
        if(evt.getClickCount()==2){
            File archive = obtenerArchivo();
            
            if (archive.exists() && archive != null)
                ruta = archive.getPath();
            
            if(ruta!=""){
                Image imagen = getToolkit().getImage(ruta);
                System.out.println();
                File file = new File(ruta);
                try {
                    jXImageView1.setImage(file);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jXImageView1MouseClicked

    private void jBPresupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPresupActionPerformed
        new jDPresupuestos(this, true, db,user.getNivelUsuario()).setVisible(true);
    }//GEN-LAST:event_jBPresupActionPerformed

    private void jBPresupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPresupKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBCompra.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPresupKeyPressed

    private void jBPresupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPresupKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBProductos.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPresupKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        /* Primero creo una tabla temporal */
        
        db.ConsActualizacion("drop table if exists tmpmax;"
                + "Create Table `tmpMax`("
                + "`Cod_producto` varchar(45) not null,"
                + "`cant_vendida` int(11) default null)"
                + "Engine= innodb default charset=latin1;");
        
        /*consulto por el rango de fechas para el reporte */
        
        jDViewDate a = new jDViewDate(this, true,"Seleccione una fecha de inicio:");
        a.setVisible(true);
        ResultSet r=null;
        
        jDViewDate b = new jDViewDate(this, true,"Seleccione una fecha de fin:");
        b.setVisible(true);

        /*consulto a la base de datos sobre los productos 
         * que fueron vendidos en el rango de fechas seleccionado*/
        
        ResultSet rs1,rs = null;
        rs=db.Listar("distinct Cod_inter_producto", "detalle_venta"," `Fecha_venta` >= '"+(a.fecha.getYear()+1900)+"-"
                  +(a.fecha.getMonth()+1)+"-"+(a.fecha.getDate())+"' and `Fecha_venta` <= '"+(b.fecha.getYear()+1900)+"-" 
                  +(b.fecha.getMonth()+1)+"-"+(b.fecha.getDate())+"'");
        try {
            /*Empiezo a cargar estos productos a la tabla temporal*/
            
            while(rs.next()){
                rs1=null;
                String prod = rs.getString("Cod_inter_producto");
                rs1=db.Listar("sum(cant_vendida)", "detalle_venta" , "where Cod_inter_producto= '"+prod+"'");
                rs1.next();
                
                db.Altas("tmpMax", "('"+prod+"','"+rs1.getInt("sum(cant_vendida)")+"')","");
            }
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        /*hago la consulta ya con la tabla temporal para pasarle los datos al reporte*/
        ResultSet rs2=null;
        rs2=db.Listar("*", "vistamvend", "");
       

        JRResultSetDataSource jrRS = new JRResultSetDataSource(rs2);
        HashMap parameters = new HashMap();
        parameters.clear();
        
        parameters.put("Tipo_de_Reporte", "Producto más vendido");
        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/ReporteVentas.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
            
            
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void habilitador(boolean ban){
        jBCompra.setVisible(ban);
        jBPacientes.setVisible(ban);
        jBPresup.setVisible(ban);
        jBProductos.setVisible(ban);
        jBVendedor.setVisible(ban);
        jBVentas.setVisible(ban);
    }
    
    private void autorizar(){
        String Nivel=user.getNivelUsuario();
        if(Nivel.equals("Administrador")){
            habilitador(true);
            jMAgrUsu.setEnabled(true);
            jmAgregarProveedor.setEnabled(true);
            jMproveedor.setEnabled(true);
            
        }else if(Nivel.equals("Depósito")){
            habilitador(false);
            jBProductos.setVisible(true);
            jMAgrUsu.setVisible(false);
            jMproveedor.setVisible(false);
            
        }else if(Nivel.equals("Ventas")){
            habilitador(false);
            jBProductos.setVisible(true);
            jBVentas.setVisible(true);
            jBCompra.setVisible(true);
            jBPresup.setVisible(true);
            jMAgrUsu.setVisible(false);
            jMproveedor.setVisible(false);
            jBPacientes.setVisible(false);
            
        }
    }
    
    public File obtenerArchivo(){
       int resultado = 0;
       JFileChooser elegir = new JFileChooser();
       
       FileView fv = new FileView() {};
       
       elegir.setFileView(fv);
       
       elegir.setFileSelectionMode(JFileChooser.FILES_ONLY);
       resultado = elegir.showOpenDialog(this);
       if(resultado == JFileChooser.CANCEL_OPTION){
           return null;
       }
       File archivo = elegir.getSelectedFile();
       if(archivo == null){
           JOptionPane.showMessageDialog(null, "Error al cargar archivo",
                        "Error", JOptionPane.ERROR_MESSAGE);
       }
       return archivo;
   }
            /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
           

            @Override
            public void run() {
               try{
                   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
               }catch(Exception e){
                   
               }
                new FramePrincipal(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMReports;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jBCompra;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModif;
    private javax.swing.JButton jBPacientes;
    private javax.swing.JButton jBPresup;
    private javax.swing.JButton jBProductos;
    private javax.swing.JButton jBVendedor;
    private javax.swing.JButton jBVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMAgrUsu;
    private javax.swing.JMenu jMCaja;
    private javax.swing.JMenuItem jMCajaDiaria;
    private javax.swing.JMenuItem jMCajaPeridic;
    private javax.swing.JMenuItem jMCambUsu;
    private javax.swing.JMenuItem jMCerrarSesion;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenuItem jMIniSesion;
    private javax.swing.JMenuItem jMOrd_p_Cod;
    private javax.swing.JMenuItem jMOrd_p_Gastado;
    private javax.swing.JMenuItem jMOrd_p_Nomb;
    private javax.swing.JMenuItem jMP_Ord_p_Cod;
    private javax.swing.JMenuItem jMP_Ord_p_Nomb;
    private javax.swing.JMenu jMVentas;
    private javax.swing.JMenuItem jMVentsDias;
    private javax.swing.JMenu jMayuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMproveedor;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private javax.swing.JMenuItem jmAgregarProveedor;
    private javax.swing.JMenu jmSesion;
    private javax.swing.JMenuItem jmVerProveedores;
    // End of variables declaration//GEN-END:variables
}
