/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAvanzado.java
 *
 * Created on 29/08/2012, 07:40:34 PM
 */
package frames;

import clases.DBConnect;
import clases.JOptionPaneConTimeOut;
import clases.mipanel;
import java.awt.Image;
import java.awt.event.KeyEvent;

/**
 *
 * @author Edgar
 */
public class FrmAvanzado extends javax.swing.JFrame {
    DBConnect db;
     Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    /** Creates new form FrmAvanzado */
    public FrmAvanzado() {
        initComponents();
        setTitle("Acceso Avanzado");
        setIconImage(imagen);
        db=new DBConnect();
        setLocationRelativeTo(null);
    }
    public void autorizar(){
        try{
            if(db.conectado(jtfip.getText(),this.jtfusuario.getText(),
                this.jpfcontraseña.getText(),jtfpuerto.getText(),jtfbd.getText()))
                {
                JOptionPaneConTimeOut a = new JOptionPaneConTimeOut();
                a.visualizaDialogo(this, "Ingresando al sistema", "Espere",1000);
                FramePrincipal f = new FramePrincipal(db);
                f.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
                f.setVisible(true);
                dispose();
            }
        }catch (Exception e){}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPimagen = new javax.swing.JPanel();
        jlblip = new javax.swing.JLabel();
        jtfip = new javax.swing.JTextField();
        jlblusuario = new javax.swing.JLabel();
        jtfusuario = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        jpfcontraseña = new javax.swing.JPasswordField();
        jlblpuerto = new javax.swing.JLabel();
        jtfpuerto = new javax.swing.JTextField();
        jlblbd = new javax.swing.JLabel();
        jtfbd = new javax.swing.JTextField();
        jbtnbasico = new javax.swing.JButton();
        jbtnaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jlblip.setText("Direccion I.P.");

        jlblusuario.setText("Usuario");

        jtfusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfusuarioKeyReleased(evt);
            }
        });

        lbl_contraseña.setText("Contraseña");

        jpfcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpfcontraseñaKeyReleased(evt);
            }
        });

        jlblpuerto.setText("Puerto");

        jtfpuerto.setText("3306");

        jlblbd.setText("Base de Datos");

        jtfbd.setText("dbeasysoft-act");

        jbtnbasico.setText("Básico");
        jbtnbasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbasicoActionPerformed(evt);
            }
        });

        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jbtnaceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnaceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPimagenLayout = new javax.swing.GroupLayout(jPimagen);
        jPimagen.setLayout(jPimagenLayout);
        jPimagenLayout.setHorizontalGroup(
            jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimagenLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPimagenLayout.createSequentialGroup()
                        .addComponent(jbtnaceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnbasico, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                    .addGroup(jPimagenLayout.createSequentialGroup()
                        .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPimagenLayout.createSequentialGroup()
                                .addComponent(jlblip, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jtfip, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(jPimagenLayout.createSequentialGroup()
                                .addComponent(jlblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jtfusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(jPimagenLayout.createSequentialGroup()
                                .addComponent(lbl_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jpfcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(jPimagenLayout.createSequentialGroup()
                                .addComponent(jlblpuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jtfpuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(jPimagenLayout.createSequentialGroup()
                                .addComponent(jlblbd, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jtfbd, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                        .addGap(1, 1, 1)))
                .addGap(67, 67, 67))
        );
        jPimagenLayout.setVerticalGroup(
            jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimagenLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblip, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtfip, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtfusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jpfcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblpuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtfpuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblbd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtfbd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnaceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jbtnbasico, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPimagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        int w=jPimagen.getWidth();
        int h=jPimagen.getHeight();
        mipanel pp = new mipanel(w,h);
        jPimagen.add(pp);
        jPimagen.repaint();
    }//GEN-LAST:event_formWindowActivated

    private void jbtnaceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnaceptarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            autorizar();
        }
}//GEN-LAST:event_jbtnaceptarKeyPressed

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        autorizar();
}//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jbtnbasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbasicoActionPerformed
        new FrmLogon().setVisible(true);
        dispose();
}//GEN-LAST:event_jbtnbasicoActionPerformed

    private void jpfcontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfcontraseñaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            autorizar();
        }
    }//GEN-LAST:event_jpfcontraseñaKeyReleased

    private void jtfusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfusuarioKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            autorizar();
        }
    }//GEN-LAST:event_jtfusuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmAvanzado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPimagen;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JButton jbtnbasico;
    private javax.swing.JLabel jlblbd;
    private javax.swing.JLabel jlblip;
    private javax.swing.JLabel jlblpuerto;
    private javax.swing.JLabel jlblusuario;
    private javax.swing.JPasswordField jpfcontraseña;
    private javax.swing.JTextField jtfbd;
    private javax.swing.JTextField jtfip;
    private javax.swing.JTextField jtfpuerto;
    private javax.swing.JTextField jtfusuario;
    private javax.swing.JLabel lbl_contraseña;
    // End of variables declaration//GEN-END:variables
}
