/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDDetalleCompra.java
 *
 * Created on 29/09/2012, 03:47:29 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;

import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Edgar
 */
public class jDDetalleCompra extends javax.swing.JDialog {
    DBConnect db;
    ResultSet r;
    String id_compra;
    DefaultTableModel m;
    int precio =0;
    Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    /** Creates new form jDDetalleCompra */
    public jDDetalleCompra(java.awt.Frame parent, boolean modal,DBConnect con,String id_compra) {
        super(parent, modal);
        initComponents();
        setIconImage(imagen);
        this.setLocationRelativeTo(null);
        this.setTitle("Detalle de Compra");
        this.db=con;
        this.id_compra=id_compra;
        jtNumCompra.setText(id_compra);
        llenarcampos();
        preparartabla();
        calcultotal();
        this.jtNumCompra.setEditable(false);
        this.jTPrecioTotal.setEditable(false);
    }
    private void preparartabla() {
         r=null;
         r=db.Listar("*", "vistacompra3", "where Id_compra='"+id_compra+"'");
            //String titulos[]={"Cod. Cliente", "Nombre", "Telefono", "Direccion"};
            m =(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Cod. Producto", "Cant. Compra", "Descripcion", "Precio Compra", "Precio Total"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTableClientes.setModel(m);
            String fila[] = new String[5];
            try {
            while(r.next()){
                fila[0]=r.getString("Cod_inter_producto");
                fila[1]=r.getString("Cant_adquirida");
                fila[2]=r.getString("Nom_producto")+" "+r.getString("Marca_producto")+" "+r.getString("detalle_producto");
                fila[3]=r.getString("Pre_compra");
                fila[4]=String.valueOf(Integer.valueOf(r.getString("Pre_compra"))*Integer.valueOf(r.getString("Cant_adquirida")));
                m.addRow(fila);
            }

        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void llenarcampos(){
      String id= jtNumCompra.getText();
      ResultSet rs = db.Listar("*", "vistacompra", "where Id_compra='"+id+"'");
        try {
            if(rs.next()){
                jFTFactura.setText(rs.getString("Factura_compra"));
                jTTipoFact.setText(rs.getString("Tipo_de_factura"));
                jTreceptor.setText(rs.getString("Nom_usu"));
                jXFecha.setDate(rs.getDate("Fecha_compra"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(jDDetalleCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void calcultotal(){
        int filas = jTableClientes.getRowCount();
        
        for(int i =0; i<filas; i++){
            int pre= Integer.valueOf(String.valueOf(jTableClientes.getValueAt(i, 4)));
            precio+=pre;
        }
        jTPrecioTotal.setText(String.valueOf(precio));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jBImprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTPrecioTotal = new javax.swing.JTextField();
        jPcompra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTreceptor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jXFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFTFactura = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jtNumCompra = new javax.swing.JTextField();
        jTProveedor = new javax.swing.JTextField();
        jTTipoFact = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Producto", "Cant. Compra", "Descripcion", "Precio Compra", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setName("jTableClientes"); // NOI18N
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableClientesMouseReleased(evt);
            }
        });
        jTableClientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableClientesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jBImprimir.setText("Imprimir Listado");
        jBImprimir.setName("jBImprimir"); // NOI18N
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");
        jLabel2.setName("jLabel2"); // NOI18N

        jTPrecioTotal.setText("0");
        jTPrecioTotal.setName("jTPrecioTotal"); // NOI18N

        jPcompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabecera de Compra"));
        jPcompra.setName("jPcompra"); // NOI18N

        jLabel3.setText("Compra N°:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Fecha:");
        jLabel4.setName("jLabel4"); // NOI18N

        jTreceptor.setName("jTreceptor"); // NOI18N

        jLabel5.setText("Receptor:");
        jLabel5.setName("jLabel5"); // NOI18N

        jXFecha.setName("jXFecha"); // NOI18N
        jXFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXFechaActionPerformed(evt);
            }
        });

        jLabel6.setText("Proveedor:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel10.setText("Factura de Compra: ");
        jLabel10.setName("jLabel10"); // NOI18N

        try {
            jFTFactura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-### #######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFactura.setName("jFTFactura"); // NOI18N

        jLabel16.setText("Tipo de Factura:");
        jLabel16.setName("jLabel16"); // NOI18N

        jtNumCompra.setName("jtNumCompra"); // NOI18N

        jTProveedor.setName("jTProveedor"); // NOI18N

        jTTipoFact.setName("jTTipoFact"); // NOI18N

        javax.swing.GroupLayout jPcompraLayout = new javax.swing.GroupLayout(jPcompra);
        jPcompra.setLayout(jPcompraLayout);
        jPcompraLayout.setHorizontalGroup(
            jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcompraLayout.createSequentialGroup()
                        .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTreceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16)))
                    .addGroup(jPcompraLayout.createSequentialGroup()
                        .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTProveedor))))
                .addGap(23, 23, 23)
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jTTipoFact))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPcompraLayout.setVerticalGroup(
            jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jXFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtNumCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTTipoFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTreceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jFTFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPcompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPcompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseReleased
        
}//GEN-LAST:event_jTableClientesMouseReleased

    private void jTableClientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableClientesPropertyChange
        
}//GEN-LAST:event_jTableClientesPropertyChange

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        try{
            r=null;
            r=db.Listar("*", "vistacompra3", "where Id_compra='"+id_compra+"'");
        } catch (Exception ex) {
            //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         JasperReport reporte;
     JasperPrint reporte_view;
     JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
     
     //Se crea un objeto HashMap
          HashMap parametros = new HashMap();
          parametros.clear();
          //parametros de entrada
         
          Integer SumaTotal = Integer.valueOf(jTPrecioTotal.getText());
          String NumCompra = jtNumCompra.getText();
          parametros.put( "SumTotal", SumaTotal+" Gs" );
          parametros.put("NumCompra",NumCompra);
     try{
         //direccion del archivo JASPER
          URL  in = this.getClass().getClassLoader().getResource("reportes/DetalleCompra.jasper");
          reporte = (JasperReport) JRLoader.loadObject( in );
          
          
          //-----------------------------------
          reporte_view = JasperFillManager.fillReport(reporte, parametros, jrRS);
          JasperViewer ventana = new JasperViewer(reporte_view,false);
          ventana.setTitle("Vista Previa");
          ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
          ventana.setVisible(true);
          
          
	  }catch (JRException E){
              JOptionPane.showMessageDialog(null, E.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
          }
}//GEN-LAST:event_jBImprimirActionPerformed

    private void jXFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXFechaActionPerformed

    }//GEN-LAST:event_jXFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDDetalleCompra dialog = new jDDetalleCompra(new javax.swing.JFrame(), true,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImprimir;
    private javax.swing.JFormattedTextField jFTFactura;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPcompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPrecioTotal;
    private javax.swing.JTextField jTProveedor;
    private javax.swing.JTextField jTTipoFact;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTreceptor;
    private org.jdesktop.swingx.JXDatePicker jXFecha;
    private javax.swing.JTextField jtNumCompra;
    // End of variables declaration//GEN-END:variables
}
