/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDNuevoUsu.java
 *
 * Created on 06/09/2012, 07:59:27 PM
 */
package frames;

import clases.DBConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgar
 */
public class JDNuevoUsu extends javax.swing.JDialog {
    private String Host;
    private String Puerto;
    private String Database;
    private String Usuario;
    private String Password;
    DBConnect connect;
    /** Creates new form JDNuevoUsu */
    public JDNuevoUsu(java.awt.Frame parent, boolean modal,DBConnect con,String frame) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Nuevo "+frame);
        this.Usuario=con.getUser();
        this.Password=con.getPass();
        jLNuevo.setText("Nuevo "+frame);
        this.connect = con;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIcon = new javax.swing.JLabel();
        jLNuevo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jLContraseña2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jPContraseña = new javax.swing.JPasswordField();
        jPContraseña2 = new javax.swing.JPasswordField();
        jPBotones = new javax.swing.JPanel();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vendedor_32x32.png"))); // NOI18N

        jLNuevo.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLNuevo.setText("Nuevo Usuario");

        jLNombre.setText("Alias:");

        jLContraseña.setText("Contraseña:");

        jLContraseña2.setText("Conf. Contraseña");

        jPBotones.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        jPBotones.add(jBAceptar);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPBotones.add(jBCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLIcon)
                        .addGap(18, 18, 18)
                        .addComponent(jLNuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLContraseña2)
                            .addComponent(jLContraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPContraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jPContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNuevo)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContraseña)
                    .addComponent(jPContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLContraseña2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        if(jPContraseña.getText().equals(jPContraseña2.getText())){
            if(connect.crearUsuario(jTNombre.getText(),jPContraseña.getText(),"Usuario")){
                this.dispose();
                JOptionPane.showMessageDialog(this, "Por favor introduzca sus datos", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                new jDNuevoPers(null, true, jTNombre.getText(), connect, jPContraseña.getText(), 1).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Alias ya existente, por favor reemplazar", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDNuevoUsu dialog = new JDNuevoUsu(new javax.swing.JFrame(), true,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLContraseña2;
    private javax.swing.JLabel jLIcon;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNuevo;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPasswordField jPContraseña;
    private javax.swing.JPasswordField jPContraseña2;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
