/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDVentas.java
 *
 * Created on 11/08/2012, 03:10:32 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.net.URL;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Edgar
 */
public class jDPresupuestos extends javax.swing.JDialog {
   private static String vend;
   Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
   DBConnect bd;
   DefaultTableModel m;
   ResultSet r;
   private static String password;
   private int i=0;
   private String Host;
   private String Puerto;
   private String Database;
   private String hoy1;
   private String fecha1;
   Date hoy;
   Date fecha;
   DateFormat hola;
   private String Nivel;
   
   
    /** Creates new form jDVentas */
    public jDPresupuestos(java.awt.Frame parent, boolean modal,DBConnect con,String Nivel) {
        super(parent, modal);
        initComponents();
        setIconImage(imagen);
        this.setLocationRelativeTo(null);
        this.setTitle("Presupuestos");
        jDPresupuestos.vend =con.getUser();
        jDPresupuestos.password=con.getPass();
        hoy= new Date();
        hola = DateFormat.getDateInstance();
        hoy1 = hola.format(hoy);
        fecha = new Date();
        jXhasta.setDate(hoy);
        fecha.setMonth(hoy.getMonth()-1);
        jXdesde.setDate(fecha);
        bd = con;
        PrepararTabla();
        this.Nivel = Nivel;
        
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmVenta = new javax.swing.JPopupMenu();
        jmVisualizarVenta = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jPBotones = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBImpreg = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jXhasta = new org.jdesktop.swingx.JXDatePicker();
        jXdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jmVisualizarVenta.setText("Visualizar Presupuesto");
        jmVisualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVisualizarVentaActionPerformed(evt);
            }
        });
        jpmVenta.add(jmVisualizarVenta);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVentas.setComponentPopupMenu(jpmVenta);
        jTVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVentas);

        jPBotones.setLayout(new java.awt.GridLayout(1, 3));

        jBNuevo.setText("Nuevo Presupuesto");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPBotones.add(jBNuevo);

        jBImpreg.setText("Imprimir el registro");
        jBImpreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImpregActionPerformed(evt);
            }
        });
        jPBotones.add(jBImpreg);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPBotones.add(jBSalir);

        jXhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXhastaActionPerformed(evt);
            }
        });

        jXdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXdesdeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualizar los presupuestos correspondientes al periodo");

        jLabel2.setText("de:");

        jLabel3.setText("al:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jXdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXdesdeActionPerformed
        // TODO add your handling code here:
        fecha= jXdesde.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXdesdeActionPerformed

    private void jXhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXhastaActionPerformed
        // TODO add your handling code here:
        hoy= jXhasta.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXhastaActionPerformed

    private void jTVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVentasMouseClicked
        if(evt.getClickCount()==2){
            System.out.println(jTVentas.getSelectedRow());
        }
        if(evt.getButton()==evt.BUTTON3){
            System.out.println("el 2");
        }
    }//GEN-LAST:event_jTVentasMouseClicked

    private void jBImpregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImpregActionPerformed
         try{
           r=null;
           r=bd.Listar("*", "vistaPresupuestos", "where `Fecha_crea_presupuesto` >= '"+(fecha.getYear()+1900)+"-"
                   +(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_crea_presupuesto<= '"+(hoy.getYear()+1900)
                   +"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())+"' order by Id_presupuesto ASC");
          

           
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        
        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/Presupuestos.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
            
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBImpregActionPerformed

    private void jmVisualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVisualizarVentaActionPerformed
        
        System.out.println(" hola :"+String.valueOf(jTVentas.getValueAt(jTVentas.getSelectedRow(), 0)));
        new jDVistaPresupuesto(null, true, bd ,String.valueOf(jTVentas.getValueAt(jTVentas.getSelectedRow(), 0))).setVisible(true);
        
    }//GEN-LAST:event_jmVisualizarVentaActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        new jDnPresupuesto(null, true, bd,Nivel).setVisible(true);
        PrepararTabla();
    }//GEN-LAST:event_jBNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDPresupuestos dialog = new jDPresupuestos(new FrmLogon(), true,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImpreg;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTVentas;
    private org.jdesktop.swingx.JXDatePicker jXdesde;
    private org.jdesktop.swingx.JXDatePicker jXhasta;
    private javax.swing.JMenuItem jmVisualizarVenta;
    private javax.swing.JPopupMenu jpmVenta;
    // End of variables declaration//GEN-END:variables

    private void PrepararTabla() {
        r= null;
        r = bd.Listar("*", "vistapresupuestos", "where `Fecha_crea_presupuesto` >= '"+(fecha.getYear()+1900)+"-"+(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_crea_presupuesto <= '"+(hoy.getYear()+1900)+"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())+"' order by Id_presupuesto ASC");
        System.out.println("where `Fecha_crea_presupuesto` > '"+(fecha.getYear()+1900)+"-"+(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_crea_presupuesto < '"+(hoy.getYear()+1900)+"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())+"'");
        String titulos[]={"Cod. Presupuesto","Fecha","Nom. Cliente","Nom. vendedor"};
        m= (new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Cod. Presupuesto","Fecha","Nom. Cliente","Nom. vendedor"})
             {
                 boolean[] canEdit = new boolean [] {false, false, false, false, false};

                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }});
        jTVentas.setModel(m);
        m= (DefaultTableModel) jTVentas.getModel();
        m.setColumnIdentifiers(titulos);
        jTVentas.setModel(m);
        String Fila[]= new String[4];
            try {
                while(r.next()){
                    Fila[0]= r.getString(1);
                    Fila[1]= r.getString(2);
                    Fila[2]= r.getString(3);
                    Fila[3]= r.getString(4);
                    m.addRow(Fila);
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage(),"Error1",JOptionPane.ERROR_MESSAGE);
               
            }
        }
    }

