/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDProveedor.java
 *
 * Created on 12-mar-2002, 9:34:37
 */

package frames;

import clases.DBConnect;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.net.URL;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author 3rott
 */
public class JDProveedor extends javax.swing.JDialog {
    private int i;
     Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    private String Usuario;
    private String Password;
    private String Host;
    private String Puerto;
    private String Database;
    
    DefaultTableModel m;
    ResultSet r;
    DBConnect db;
    int Control=0;
    /** Creates new form JDProveedor */
    public JDProveedor(java.awt.Frame parent, boolean modal,DBConnect con,int call) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(imagen);
        setTitle("Proveedores");
        this.Usuario = con.getUser();
        this.Password = con.getPass();

        db= con;
        preparartabla();
        this.Control = call;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPmenucliente = new javax.swing.JPopupMenu();
        ModificarProveedor = new javax.swing.JMenuItem();
        Eliminar_Proveedor = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        JbCancelar = new javax.swing.JButton();
        jTbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        ModificarProveedor.setText("Modificar Proveedor");
        ModificarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarProveedorMouseClicked(evt);
            }
        });
        ModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProveedorActionPerformed(evt);
            }
        });
        jPmenucliente.add(ModificarProveedor);

        Eliminar_Proveedor.setText("Eliminar Proveedor");
        Eliminar_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_ProveedorMouseClicked(evt);
            }
        });
        Eliminar_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ProveedorActionPerformed(evt);
            }
        });
        jPmenucliente.add(Eliminar_Proveedor);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Proveedor", "Nombre", "Telefono", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setComponentPopupMenu(jPmenucliente);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableClientesMouseReleased(evt);
            }
        });
        jTableClientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableClientesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jBModificar.setText("Modificar Proveedor");
        jBModificar.setToolTipText("Modificar datos del Cliente");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar);

        jBImprimir.setText("Imprimir Listado");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jBImprimir);

        JbCancelar.setText("Cancelar");
        JbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(JbCancelar);

        jTbuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTbuscarCaretUpdate(evt);
            }
        });
        jTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTbuscarKeyTyped(evt);
            }
        });

        jLabel1.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseReleased

}//GEN-LAST:event_jTableClientesMouseReleased

    private void jTableClientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableClientesPropertyChange

}//GEN-LAST:event_jTableClientesPropertyChange

    private void JbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarActionPerformed
        
        this.dispose();
        
        
}//GEN-LAST:event_JbCancelarActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        try{
           r=null;
           r=db.Listar("*", "proveedor", "");
          

           
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();

        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/proveedores.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);

             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_jBImprimirActionPerformed

    private void jTbuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTbuscarCaretUpdate
        // TODO add your handling code here:
        int fil, col=1;
        //Limpia selección de la tabla
        jTableClientes.clearSelection();
        String titulos[]={"Cod. Proveedor", "Nombre", "Telefono", "Direccion"};
        m = new DefaultTableModel(null, titulos);
        jTableClientes.setModel(m); r=null;
        r=db.Listar("*", "proveedor", " where Nom_proveedor like \""+ jTbuscar.getText()+"%\"");
        String fila[] = new String[4];
        try {
            while(r.next()){
                fila[0]=r.getString(1);
                fila[1]=r.getString(2);
                fila[2]=r.getString(3);
                fila[3]=r.getString(4);
                m.addRow(fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jTbuscarCaretUpdate

    private void jTbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscarKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTbuscarKeyTyped

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
       
        if(jTableClientes.getSelectedRow()>(-1)){
            this.dispose();
            String cod= String.valueOf(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0));
            if(i==0){
                new jDModProveedor(null, true, Usuario,Password, Control,cod).setVisible(true);
            }else{
                new jDModProveedor(null, true, Host, Usuario, Password, Puerto, Database, Control,cod).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un personal", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void ModificarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarProveedorMouseClicked
        
}//GEN-LAST:event_ModificarProveedorMouseClicked

    private void ModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProveedorActionPerformed
        if(jTableClientes.getSelectedRow()>(-1)){
            this.dispose();
            String cod= String.valueOf(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0));
            System.out.println(cod);
            if(i==0){
                new jDModProveedor(null, true, Usuario,Password, Control,cod).setVisible(true);
            }else{
                new jDModProveedor(null, true, Host, Usuario, Password, Puerto, Database, Control,cod).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un personal", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_ModificarProveedorActionPerformed

    private void Eliminar_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_ProveedorMouseClicked
        
}//GEN-LAST:event_Eliminar_ProveedorMouseClicked

    private void Eliminar_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ProveedorActionPerformed
        if(jTableClientes.getSelectedRow()>(-1)){
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar al cliente?");
            if(resp==JOptionPane.YES_OPTION){
                String cod= String.valueOf(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0));
                if(db.Bajas("proveedor", "where Id_proveedor='"+cod+"'")){
                    JOptionPane.showMessageDialog(null, "Proveedor "+cod+" eliminado", "Exito", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un personal", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_Eliminar_ProveedorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDProveedor dialog = new JDProveedor(new javax.swing.JFrame(), true,null,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar_Proveedor;
    private javax.swing.JButton JbCancelar;
    private javax.swing.JMenuItem ModificarProveedor;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPmenucliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTbuscar;
    // End of variables declaration//GEN-END:variables

    private void preparartabla() {
         r=null;
         r=db.Listar("*", "proveedor", "");
            //String titulos[]={"Cod. Cliente", "Nombre", "Telefono", "Direccion"};
            m =(DefaultTableModel) jTableClientes.getModel();
            jTableClientes.setModel(m);
            String fila[] = new String[4];
            try {
            while(r.next()){
                fila[0]=r.getString(1);
                fila[1]=r.getString(2);
                fila[2]=r.getString(3);
                fila[3]=r.getString(4);
                 m.addRow(fila);
            }

        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
