/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDConsVenta.java
 *
 * Created on 24/01/2014, 04:11:00 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.awt.event.KeyEvent;

/**
 *
 * @author Edgar
 */
public class JDPresuVenta extends javax.swing.JDialog {
    private DBConnect con;
    private Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    private String Nivel;
    /** Creates new form JDConsVenta */
    public JDPresuVenta(java.awt.Frame parent, boolean modal, DBConnect db,String Nivel) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consulta");
        this.setIconImage(imagen);
        this.con = db;
        this.Nivel= Nivel;
        jRBListVentas.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBoto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRBListVentas = new javax.swing.JRadioButton();
        jRBListPresu = new javax.swing.JRadioButton();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("¿Qué desea ver?");
        jLabel1.setName("jLabel1"); // NOI18N

        GrupoBoto.add(jRBListVentas);
        jRBListVentas.setText("Lista de Ventas");
        jRBListVentas.setName("jRBListVentas"); // NOI18N
        jRBListVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBListVentasKeyPressed(evt);
            }
        });

        GrupoBoto.add(jRBListPresu);
        jRBListPresu.setText("Lista de Presupuestos");
        jRBListPresu.setName("jRBListPresu"); // NOI18N
        jRBListPresu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBListPresuKeyPressed(evt);
            }
        });

        jBAceptar.setText("Aceptar");
        jBAceptar.setName("jBAceptar"); // NOI18N
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setName("jBCancelar"); // NOI18N
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelar))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBListVentas)
                            .addComponent(jRBListPresu))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jRBListVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBListPresu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        this.dispose();
        if(jRBListVentas.isSelected()){
            new jDVentas(null, true, con,Nivel).setVisible(true);
        }else if(jRBListPresu.isSelected()){
            new jDPresupuestos(null, true,con,Nivel).setVisible(true);
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jRBListVentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBListVentasKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_DOWN || evt.getKeyCode()== KeyEvent.VK_UP){
            jRBListPresu.requestFocus();
            jRBListPresu.setSelected(true);
        }
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            this.jBAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jRBListVentasKeyPressed

    private void jRBListPresuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBListPresuKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_DOWN || evt.getKeyCode()== KeyEvent.VK_UP){
            jRBListVentas.requestFocus();
            jRBListVentas.setSelected(true);
        }
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            this.jBAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jRBListPresuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDPresuVenta dialog = new JDPresuVenta(new javax.swing.JFrame(), true, null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBoto;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBListPresu;
    private javax.swing.JRadioButton jRBListVentas;
    // End of variables declaration//GEN-END:variables
}
