/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDVendedor.java
 *
 * Created on 11/08/2012, 08:10:47 AM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar
 */
public class jDVendedor extends javax.swing.JDialog {
    Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    ResultSet r;
    DBConnect bd;
    DefaultTableModel m;
    private String Host;
    private String Puerto;
    private String Database;
    private String Usuario;
    private String Password;
    /** Creates new form jDVendedor */
    public jDVendedor(java.awt.Frame parent, boolean modal,String usu,String pass) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(imagen);
        setTitle("Personal");
        bd = new DBConnect();
        bd.conectado(usu, pass);
        PrepararTabla();
        this.Usuario=usu;
        this.Password=pass;
    }
    public jDVendedor(java.awt.Frame parent, boolean modal,String host,String usu,String pass,String puerto,String database) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(imagen);
        this.Host=host;
        this.Puerto=puerto;
        this.Database=database;
        this.Password=pass;
        this.Usuario=usu;
        setTitle("Personal");
        bd = new DBConnect();
        bd.conectado(host,usu, pass,puerto,database);
        PrepararTabla();
        PrepararTabla();
    }
     private void PrepararTabla() {
          try {
                r= null;
                r = bd.Listar("*", "usuario", "");
                String titulos[]={"Cod. Usuario","Nombre","Telefono","Direccion","Nivel"};
                
                    m = (DefaultTableModel) jTVentas.getModel();
                    m.setColumnIdentifiers(titulos);
                    jTVentas.setModel(m);
                    
                String Fila[]= new String[5];
           
                while(r.next()){
                    Fila[0]= r.getString("Id_usu");
                    Fila[1]= r.getString("Nom_usu");
                    Fila[2]= r.getString("Direc_usu");
                    Fila[3]= r.getString("Tel_usu");
                    Fila[4]= r.getString("Nivel_Usuario");
                    m.addRow(Fila);

                }
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage(),"Error1",JOptionPane.ERROR_MESSAGE);
               
            }
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        query1 = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery("");
        jPVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jPBotones = new javax.swing.JPanel();
        jBNueva = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBModVenta = new javax.swing.JButton();
        jBImpreg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);

        jPVentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTVentas);

        jPBotones.setLayout(new java.awt.GridLayout(2, 3));

        jBNueva.setText("Nuevo Personal");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });
        jPBotones.add(jBNueva);

        jBSalir.setText("Salir");
        jPBotones.add(jBSalir);

        jBModVenta.setText("Modificar Datos");
        jPBotones.add(jBModVenta);

        jBImpreg.setText("Imprimir el registro");
        jPBotones.add(jBImpreg);

        javax.swing.GroupLayout jPVentasLayout = new javax.swing.GroupLayout(jPVentas);
        jPVentas.setLayout(jPVentasLayout);
        jPVentasLayout.setHorizontalGroup(
            jPVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPBotones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVentasLayout.setVerticalGroup(
            jPVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
        this.dispose();
        new jDNuevoPers(null, true, Usuario,bd,"",0).setVisible(true);
    }//GEN-LAST:event_jBNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDVendedor dialog = new jDVendedor(new javax.swing.JFrame(), true,"","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImpreg;
    private javax.swing.JButton jBModVenta;
    private javax.swing.JButton jBNueva;
    private javax.swing.JButton jBSalir;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPVentas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTVentas;
    private javax.persistence.Query query1;
    // End of variables declaration//GEN-END:variables
}
